//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasWebApi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CANVAS_Model_Entities : DbContext
    {
        public CANVAS_Model_Entities()
            : base("name=CANVAS_Model_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uniCanvasCarrera> uniCanvasCarreras { get; set; }
        public virtual DbSet<uniCanvasCurso> uniCanvasCursos { get; set; }
        public virtual DbSet<uniCanvasCursosSeccione> uniCanvasCursosSecciones { get; set; }
        public virtual DbSet<uniCanvasEnrolamiento> uniCanvasEnrolamientos { get; set; }
        public virtual DbSet<uniCanvasUsuario> uniCanvasUsuarios { get; set; }
        public virtual DbSet<uniMateria> uniMaterias { get; set; }
    
        public virtual ObjectResult<sp_uni_canvas_sincronizacion_Result> sp_uni_canvas_sincronizacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_uni_canvas_sincronizacion_Result>("sp_uni_canvas_sincronizacion");
        }
    
        public virtual int sp_ins_uniCanvas_cursos_secciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_uniCanvas_cursos_secciones");
        }
    
        public virtual int sp_ins_uniCanvas_usuarios_enrolamientos(Nullable<int> ciclo, Nullable<int> cuatri)
        {
            var cicloParameter = ciclo.HasValue ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(int));
    
            var cuatriParameter = cuatri.HasValue ?
                new ObjectParameter("cuatri", cuatri) :
                new ObjectParameter("cuatri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_uniCanvas_usuarios_enrolamientos", cicloParameter, cuatriParameter);
        }
    
        public virtual ObjectResult<sp_get_uniCanvas_ws_cursos_Result> sp_get_uniCanvas_ws_cursos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_uniCanvas_ws_cursos_Result>("sp_get_uniCanvas_ws_cursos");
        }
    
        public virtual ObjectResult<sp_get_uniCanvas_ws_enrolamientos_Result> sp_get_uniCanvas_ws_enrolamientos(string operacion)
        {
            var operacionParameter = operacion != null ?
                new ObjectParameter("operacion", operacion) :
                new ObjectParameter("operacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_uniCanvas_ws_enrolamientos_Result>("sp_get_uniCanvas_ws_enrolamientos", operacionParameter);
        }
    
        public virtual ObjectResult<sp_get_uniCanvas_ws_secciones_Result> sp_get_uniCanvas_ws_secciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_uniCanvas_ws_secciones_Result>("sp_get_uniCanvas_ws_secciones");
        }
    
        public virtual ObjectResult<sp_get_uniCanvas_ws_usuarios_Result> sp_get_uniCanvas_ws_usuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_uniCanvas_ws_usuarios_Result>("sp_get_uniCanvas_ws_usuarios");
        }
    }
}
