//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniCanvasUsuario
    {
        public int IDAcademico { get; set; }
        public Nullable<int> IDCanvas { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
