//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniMateria
    {
        public string codmat { get; set; }
        public Nullable<int> periodo { get; set; }
        public string nombre { get; set; }
        public string coddep { get; set; }
        public string usrnom { get; set; }
        public Nullable<System.DateTime> ftrn { get; set; }
        public Nullable<int> vigente { get; set; }
        public string auxi { get; set; }
        public Nullable<double> hsteoricas { get; set; }
        public Nullable<double> hspracticas { get; set; }
        public Nullable<double> hslaboratorio { get; set; }
        public Nullable<double> hscampo { get; set; }
        public Nullable<double> hsclinica { get; set; }
        public string ConceptoId { get; set; }
        public Nullable<bool> EsOptativaGeneral { get; set; }
    }
}
